name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt

      - uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: |
          ./gradlew assemble

      - name: Test with Gradle
        run: |
          unset GITHUB_ACTIONS
          ./gradlew test
